export const CREATE_CONTACT = "CREATE_CONTACT";
export const GET_SINGLE_CONTACT = "GET_SINGLE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
